---
apiVersion: riskified.com/v1alpha1
kind: DynamicEnv
metadata:
  name: dynamicenv-simple-test
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: details-default-dynamicenv-simple-test
  namespace: simple-test
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: details-default-dynamicenv-simple-test
  namespace: simple-test
