apiVersion: v1
kind: Namespace
metadata:
  name: add-remove-subsets
---
apiVersion: v1
kind: Service
metadata:
  name: details
  namespace: add-remove-subsets
  labels:
    app: details
    service: details
spec:
  ports:
    - port: 9080
      name: http
  selector:
    app: details
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: bookinfo-details
  namespace: add-remove-subsets
  labels:
    account: details
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: details
  namespace: add-remove-subsets
  labels:
    app: details
    version: shared
spec:
  replicas: 1
  selector:
    matchLabels:
      app: details
      version: shared
  template:
    metadata:
      labels:
        app: details
        version: shared
    spec:
      serviceAccountName: bookinfo-details
      containers:
        - name: details
          image: docker.io/istio/examples-bookinfo-details-v1:1.16.2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9080
          securityContext:
            runAsUser: 1000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: details-worker
  namespace: add-remove-subsets
  labels:
    app: details
    version: shared
spec:
  replicas: 2
  selector:
    matchLabels:
      app: details-worker
      version: shared
  template:
    metadata:
      labels:
        app: details-worker
        version: shared
    spec:
      serviceAccountName: bookinfo-details
      containers:
        - name: details
          image: docker.io/istio/examples-bookinfo-details-v1:1.16.2
          imagePullPolicy: IfNotPresent
          securityContext:
            runAsUser: 1000
---
##################################################################################################
# Ratings service
##################################################################################################
apiVersion: v1
kind: Service
metadata:
  name: ratings
  namespace: add-remove-subsets
  labels:
    app: ratings
    service: ratings
spec:
  ports:
    - port: 9080
      name: http
  selector:
    app: ratings
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: bookinfo-ratings
  namespace: add-remove-subsets
  labels:
    account: ratings
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ratings
  namespace: add-remove-subsets
  labels:
    app: ratings
    version: shared
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ratings
      version: shared
  template:
    metadata:
      labels:
        app: ratings
        version: shared
    spec:
      serviceAccountName: bookinfo-ratings
      containers:
        - name: ratings
          image: docker.io/istio/examples-bookinfo-ratings-v1:1.16.2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9080
          securityContext:
            runAsUser: 1000
---
##################################################################################################
# Reviews service
##################################################################################################
apiVersion: v1
kind: Service
metadata:
  name: reviews
  namespace: add-remove-subsets
  labels:
    app: reviews
    service: reviews
spec:
  ports:
    - port: 9080
      name: http
  selector:
    app: reviews
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: bookinfo-reviews
  namespace: add-remove-subsets
  labels:
    account: reviews
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reviews
  namespace: add-remove-subsets
  labels:
    app: reviews
    version: shared
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reviews
      version: shared
  template:
    metadata:
      labels:
        app: reviews
        version: shared
    spec:
      serviceAccountName: bookinfo-reviews
      containers:
        - name: reviews
          image: docker.io/istio/examples-bookinfo-reviews-v2:1.16.2
          imagePullPolicy: IfNotPresent
          env:
            - name: LOG_DIR
              value: "/tmp/logs"
          ports:
            - containerPort: 9080
          volumeMounts:
            - name: tmp
              mountPath: /tmp
            - name: wlp-output
              mountPath: /opt/ibm/wlp/output
          securityContext:
            runAsUser: 1000
      volumes:
        - name: wlp-output
          emptyDir: {}
        - name: tmp
          emptyDir: {}
---
##################################################################################################
# Productpage services
##################################################################################################
apiVersion: v1
kind: Service
metadata:
  name: productpage
  namespace: add-remove-subsets
  labels:
    app: productpage
    service: productpage
spec:
  ports:
    - port: 9080
      name: http
  selector:
    app: productpage
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: bookinfo-productpage
  namespace: add-remove-subsets
  labels:
    account: productpage
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: productpage
  namespace: add-remove-subsets
  labels:
    app: productpage
    version: shared
spec:
  replicas: 1
  selector:
    matchLabels:
      app: productpage
      version: shared
  template:
    metadata:
      labels:
        app: productpage
        version: shared
    spec:
      serviceAccountName: bookinfo-productpage
      containers:
        - name: productpage
          image: docker.io/istio/examples-bookinfo-productpage-v1:1.16.2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9080
          volumeMounts:
            - name: tmp
              mountPath: /tmp
          securityContext:
            runAsUser: 1000
      volumes:
        - name: tmp
          emptyDir: {}
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: productpage
  namespace: add-remove-subsets
spec:
  host: productpage
  subsets:
    - name: shared
      labels:
        version: shared
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: reviews
  namespace: add-remove-subsets
spec:
  host: reviews
  subsets:
    - name: shared
      labels:
        version: shared
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: ratings
  namespace: add-remove-subsets
spec:
  host: ratings
  subsets:
    - name: shared
      labels:
        version: shared
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: details
  namespace: add-remove-subsets
spec:
  host: details
  subsets:
    - name: shared
      labels:
        version: shared
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: productpage
  namespace: add-remove-subsets
spec:
  hosts:
    - productpage
  http:
    - route:
        - destination:
            host: productpage
            subset: shared
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: reviews
  namespace: add-remove-subsets
spec:
  hosts:
    - reviews
  http:
    - route:
        - destination:
            host: reviews
            subset: shared
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: ratings
  namespace: add-remove-subsets
spec:
  hosts:
    - ratings
  http:
    - route:
        - destination:
            host: ratings
            subset: shared
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: details
  namespace: add-remove-subsets
spec:
  hosts:
    - details
  http:
    - route:
        - destination:
            host: details
            subset: shared
---
apiVersion: riskified.com/v1alpha1
kind: DynamicEnv
metadata:
  name: dynamicenv-add-remove-subsets
spec:
  istioMatches:
    - headers:
        end-user:
          prefix: jason
  subsets:
    - name: details
      namespace: add-remove-subsets
      containers:
        - containerName: details
          image: docker.io/istio/examples-bookinfo-details-v2:1.16.2
          env:
            - name: TOPIC_NAME
              value: test