---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: details-default-dynamicenv-add-remove-subsets
  namespace: add-remove-subsets
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: details-worker-default-dynamicenv-add-remove-subsets
  namespace: add-remove-subsets
...
