---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-riskified-com-v1alpha1-dynamicenv
  failurePolicy: Fail
  name: vdynamicenv.kb.io
  rules:
  - apiGroups:
    - riskified.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - dynamicenvs
  sideEffects: None
