---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: details-default-accidental-resources-deletion
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: reviews
  namespace: accidental-resources-deletion