# permissions for end users to edit dynamicenvs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dynamicenv-editor-role
rules:
- apiGroups:
  - riskified.com
  resources:
  - dynamicenvs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - riskified.com
  resources:
  - dynamicenvs/status
  verbs:
  - get
