# permissions for end users to view dynamicenvs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dynamicenv-viewer-role
rules:
- apiGroups:
  - riskified.com
  resources:
  - dynamicenvs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - riskified.com
  resources:
  - dynamicenvs/status
  verbs:
  - get
