---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: test-app-vs
  namespace: delegate-virtual-service-2
spec:
  hosts:
    - test-app-service.delegate-virtual-service.svc.cluster.local
  http:
    - headers:
        request:
          add:
            x-request-start: t=%START_TIME(%s.%3f)%
          set:
            X-FORWARDED-PROTO: https
        response:
          remove:
            - x-envoy-upstream-healthchecked-cluster
            - x-envoy-upstream-service-time
      match:
        - gateways:
            - mesh
          headers:
            end-user:
              prefix: jason
#      name: dynamic-environment-default-dynamicenv-delegate-virtual-service-test-app-eab8f3914d
      route:
        - destination:
            host: test-app-service.delegate-virtual-service.svc.cluster.local
            port:
              number: 80
            subset: default-dynamicenv-delegate-virtual-service
    - headers:
        request:
          add:
            x-request-start: t=%START_TIME(%s.%3f)%
          set:
            X-FORWARDED-PROTO: https
        response:
          remove:
            - x-envoy-upstream-healthchecked-cluster
            - x-envoy-upstream-service-time
      match:
        - gateways:
            - mesh
      name: in-cluster-default
      route:
        - destination:
            host: test-app-service.delegate-virtual-service.svc.cluster.local
            port:
              number: 80
            subset: shared
          weight: 100
    - delegate:
        name: test-app-vs-delegated
        namespace: delegate-virtual-service
      match:
        - uri:
            prefix: /nisan
    - delegate:
        name: does-not-exist-delegate
        namespace: delegate-virtual-service
      match:
        - uri:
            prefix: /adi
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: test-app-vs-delegated
  namespace: delegate-virtual-service
spec:
  http:
    - headers:
        request:
          add:
            x-request-start: t=%START_TIME(%s.%3f)%
          set:
            X-FORWARDED-PROTO: https
        response:
          remove:
            - x-envoy-upstream-healthchecked-cluster
            - x-envoy-upstream-service-time
      match:
        - headers:
            end-user:
              prefix: jason
          uri:
            prefix: /haim
#      name: dynamic-environment-default-dynamicenv-delegate-virtual-service-test-app-d559661c4d
      route:
        - destination:
            host: test-app-service.delegate-virtual-service.svc.cluster.local
            port:
              number: 80
            subset: default-dynamicenv-delegate-virtual-service
    - headers:
        request:
          add:
            x-request-start: t=%START_TIME(%s.%3f)%
          set:
            X-FORWARDED-PROTO: https
        response:
          remove:
            - x-envoy-upstream-healthchecked-cluster
            - x-envoy-upstream-service-time
      match:
        - uri:
            prefix: /haim
      name: haim
      route:
        - destination:
            host: test-app-service.delegate-virtual-service.svc.cluster.local
            port:
              number: 80
            subset: shared
          weight: 100
---
apiVersion: riskified.com/v1alpha1
kind: DynamicEnv
metadata:
  name: dynamicenv-delegate-virtual-service
  namespace: default
status:
  subsetsStatus:
    test-app-default-dynamicenv-delegate-virtual-service:
      subsetErrors:
        virtualServices:
          - error: 'Wierd, Couldn''t find a service with name: does-not-exist-delegate,
              namespace: delegate-virtual-service, in the service list'
          - error: Delegate (delegate-virtual-service/does-not-exist-delegate) not found
      virtualServices:
        - name: test-app-vs
          namespace: delegate-virtual-service-2
          status: running
        - name: test-app-vs-delegated
          namespace: delegate-virtual-service
          status: running
...