apiVersion: riskified.com/v1alpha1
kind: DynamicEnv
metadata:
  name: dynamicenv-consumers-with-and-without-errors
  namespace: default
status:
  state: degraded
  totalCount: 3
  totalReady: 2
  consumersStatus:
    details-worker-default-dynamicenv-consumers-with-and-without-er:
      name: details-worker-default-dynamicenv-consumers-with-and-without-er
      namespace: consumers-with-and-without-errors
      status: running
      hash: -7893432429265961114
    details-worker-invalid-default-dynamicenv-consumers-with-and-without-er:
      errors:
        - error: 'couldn''t find the deployment we need to override (name: details-worker-invalid,
          ns: consumers-with-and-without-errors), Deployment.apps "details-worker-invalid"
          not found'
