apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: dynamic-environment-operator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: DynamicEnv is the Schema for the dynamicenvs API
      displayName: Dynamic Env
      kind: DynamicEnv
      name: dynamicenvs.riskified.com
      version: v1alpha1
  description: Dynamic environment operator for Kubernetes
  displayName: dynamic-environment-operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - Istio
  - Test
  links:
  - name: Dynamic Environment Operator
    url: https://dynamic-environment-operator.domain
  maturity: alpha
  provider:
    name: riskified
  version: 0.0.0
