apiVersion: riskified.com/v1alpha1
kind: DynamicEnv
metadata:
  name: dynamicenv-sample
spec:
  istioMatches:
    - headers:
        end-user:
          exact: jason
  subsets:
    - name: "details"
      namespace: "services"
      initContainer:
        containerName: install
        image: docker.io/istio/busybox:latest
        env:
          - name: TOPIC_NAME 
            value: test