---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    riskified.com/dynamic-environment: "default/dynamicenv-watch-annotations"
  labels:
    app: details
    version: default-dynamicenv-watch-annotations
  name: details-default-dynamicenv-watch-annotations
  namespace: watch-annotations
spec:
  template:
    spec:
      containers:
        - env:
          - name: TOPIC_NAME
            value: test2
status:
  replicas: 1
...