---
apiVersion: riskified.com/v1alpha1
kind: DynamicEnv
metadata:
  name: dynamicenv-replica-size
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: details-default-dynamicenv-replica-size
  namespace: replica-size
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: details-default-dynamicenv-replica-size
  namespace: replica-size