---
apiVersion: riskified.com/v1alpha1
kind: DynamicEnv
metadata:
  name: dynamicenv-multiple-services-per-deployment
  namespace: default
status:
  state: ready
  subsetsStatus:
    multiple-services-per-deployment/details:
      deployment:
        name: details-default-dynamicenv-multiple-services-per-deploym
        namespace: multiple-services-per-deployment
        status: running
      destinationRules:
        - name: details-default-dynamicenv-multiple-services-per-deploym-details
          namespace: multiple-services-per-deployment
          status: running
        - name: details-default-dynamicenv-multiple-services-per-deploym-details-alt
          namespace: multiple-services-per-deployment
          status: ignored-missing-destination-rule
#      virtualServices:
#        - name: details
#          namespace: multiple-services-per-deployment
#          status: running
  totalCount: 1
  totalReady: 1
...