apiVersion: v1
kind: Service
metadata:
  name: {{ template "dynamic-environment-operator.webhookService" . }}
  namespace: {{ .Release.Namespace }}
  {{- with .Values.serviceAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "dynamic-environment-operator.labels" . | nindent 4 }}
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 9443
  selector:
    {{- include "dynamic-environment-operator.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "dynamic-environment-operator.fullname" . }}
  namespace: {{ .Release.Namespace }}
    {{- with .Values.serviceAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "dynamic-environment-operator.labels" . | nindent 4 }}
spec:
  ports:
    - port: 8080
      name: metrics-server
      targetPort: metrics-server
  selector:
    {{- include "dynamic-environment-operator.selectorLabels" . | nindent 4 }}