name: tests
on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  kuttl:
    uses: ./.github/workflows/kuttl_workflow.yaml
    with:
      istio_ver: ''
      kind_image: ''
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install asdf & tools
        uses: asdf-vm/actions/install@v2
      - run: make test lint
  pre-merge-tasks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install asdf & tools
        uses: asdf-vm/actions/install@v2
      - name: Verify pre-merge tasks are committed.
        run: |
          make prepare
          make pre-merge
          if [[ `git status --porcelain` ]]; then
            echo "There seem to be changes after 'pre-merge' tasks, did you run these tasks before committing?"
            exit 1
          else
            echo "Pre-merge tasks are committed :)"
          fi
