---
apiVersion: v1
kind: Namespace
metadata:
  name: update-subset-resources
  labels:
    istio-injection: enabled
---
apiVersion: v1
kind: Service
metadata:
  name: details
  namespace: update-subset-resources
  labels:
    app: details
    service: details
spec:
  ports:
    - port: 9080
      name: http
  selector:
    app: details
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: bookinfo-details
  namespace: update-subset-resources
  labels:
    account: details
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: details
  namespace: update-subset-resources
  labels:
    app: details
    version: shared
spec:
  replicas: 1
  selector:
    matchLabels:
      app: details
      version: shared
  template:
    metadata:
      labels:
        app: details
        version: shared
    spec:
      serviceAccountName: bookinfo-details
      containers:
        - name: details
          image: docker.io/istio/examples-bookinfo-details-v1:1.16.2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9080
          securityContext:
            runAsUser: 1000
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: details
  namespace: update-subset-resources
spec:
  host: details
  subsets:
    - name: shared
      labels:
        version: shared
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: details
  namespace: update-subset-resources
spec:
  hosts:
    - details
  http:
    - route:
        - destination:
            host: details
            subset: shared
---
apiVersion: riskified.com/v1alpha1
kind: DynamicEnv
metadata:
  name: dynamicenv-update-subset-resources
spec:
  istioMatches:
    - headers:
        end-user:
          prefix: jason
  subsets:
    - name: details
      namespace: update-subset-resources
      containers:
        - containerName: details
          image: docker.io/istio/examples-bookinfo-details-v2:1.16.2
          env:
            - name: TOPIC_NAME
              value: test
...
